name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4'
        
    - name: Install dependencies
      run: gem install simplecov standard
      
    - name: Check code formatting
      run: standardrb
      
    - name: Run tests
      run: rake test